### ISSUE TITLE
HTML/CSS/JS lab hours Wed + Thurs, 4-5pm

### ISSUE THREAD

**Issue by jueyang** [jueyang/know-your-tools#1]
Hey everybody,

This is just a reminder that there'll be lab hours from 4-5pm on Wednesday and Thursday this week. Room 436 (your classroom for html/css/js) is available during those hours, so I plan to be there. If you have any questions regarding installation or your snowflake, come by.

@allegra15
@jonathancarey
@alizachasan
@asiaewart
@nmadov
@desialex17
@catharob
@dannis51
@helinaselemon
@julianason
@zachwass
@sarahsyu
@dngrdangerfield

cc @melouttit

ref https://github.com/melouttit/cuny-programming

**Comment by jueyang** [comment]
@zachwasss re-mentioning you with the correct handle. See comment above.

**Comment by jueyang** [comment]
Also, I added the `ls` command in your CLI assignment: https://github.com/jueyang/know-your-tools/blob/master/week1.md#ok-time-for-homework-of-the-week

I've also included a little spiel on good file naming conventions under [Tips and tricks](https://github.com/jueyang/know-your-tools/blob/master/week1.md#tips-and-tricks), which will help you become more organized with your files (hence less confusion when using CLI.) :+1: 

If you've already completed the exercise, I recommend you doing it again with some `ls` in it, just so you can get familiar with CLI. (Goal is the practice, not the final product :) The more comfortable you are in CLI, the more productive you'll be over the next few classes. 

Or if you are bored by the exercise, try complete your everyday tasks through iTerm with the introduced commands, and see how that affects your workflow on a computer.

**Comment by jueyang** [comment]
Alright, hope y'all are ready for class tonight. Just pushed week 2 material for GitHub and a bit on file structure to add to your html/css adventure :golf: 

https://github.com/jueyang/know-your-tools/blob/master/week2.md

See you tonight!

**Comment by dngrdangerfield** [comment]
Hey Jue,
Are you going to be at school around 3pm today? I'm having a hard time
installing homebrew on my system, and wanted to swing by your office/room.

Best,
Maya

_Maya Dangerfield_

http://about.me/mayadangerfield

**Comment by jueyang** [comment]
@dngrdangerfield for sure. Check the slack channel for deats!

**Comment by jueyang** [comment]
Good job yesterday, everyone. I'll be adding a few things to the week2.md based on yesterday's class and update you shortly. Have a good one :cactus: :cactus: :cactus:
