### ISSUE TITLE
Meeting

### ISSUE THREAD

**Issue by helinaselemon** [jueyang/know-your-tools#2]
I have new issues. This is Helina, by the way.

**Comment by jueyang** [comment]
Hey @helinaselemon. Let's meet. As a prep, could you post back screenshots when you're trying to install `homebrew`? Would like to like at the error messages before we meet. Thx!

**Comment by helinaselemon** [comment]
@jueyang 
![screenshot 2015-02-10 00 37 21](https://cloud.githubusercontent.com/assets/10820595/6122141/1d172246-b0bd-11e4-8231-1b38ba0cc150.png)

Good news: I think I know why I can't download home-brew. I have two (or maybe more) sets of User/Applications/etc. folders. I think I accidentally backed up my original username (hselemon) on my external hard drive. I've actually searched the Applications folder and found a number of them. 

Bad news: I can't seem to get the system to go down the route I want it to. 

Let's talk whenever you're soonest available.

**Comment by jueyang** [comment]
Hey @helinaselemon. Do you have time to stop by between 3-5:30pm? 

Before that, if you would like to brave [this doc](http://apple.stackexchange.com/questions/42127/homebrew-permissions-multiple-users-needing-to-brew-update) and get an idea of setting things up for multiple users (your computer and your harddrive,) feel free to do so. But that's totally optional...

**Comment by jueyang** [comment]
Turned out to be an SSL prob :) Solved.
